---
- name: Build and push Docker images
  hosts: all
  become: yes
  
  tasks:
   
  - name: Check if directory exists
    stat:
      path: /PFE-Back
    register: repo_stat

  - name: Clone repository
    shell: |
      git clone https://github.com/BenAmor1/PFE-Back.git /PFE-Back
    when: repo_stat.stat.exists == False

  - name: Pull repository
    shell: |
      cd /PFE-Back
      git pull 
    when: repo_stat.stat.exists == True
    
  - name: Build the Docker image
    shell: | 
      cd /PFE-Back
      docker build . -t reactback/image
   
  - name: Tag the image
    shell: | 
      cd /PFE-Back
      docker tag reactback/image beffa/project_pfe-2022:react_backV1
  
  - name: Push the image to Docker Hub
    shell: docker push beffa/project_pfe-2022:react_backV1
    
